### ISSUE TITLE
При отправке любого sequence_number (--sn) в ручную, в bind всегда подставляется 0.

### ISSUE THREAD

**Issue by Rinat-R** [funbox/smppsend#15]
При отправке через опцию --sn, например

`smppsend --submit-sm --source-addr test --destination-addr 71234567890 --source-addr-ton 5 --source-addr-npi 0 --dest-addr-ton 1 --dest-addr-npi 1 --data-coding 0 --host smppex.rubybox.ru --port 2775 --system-id testsid --password password --bind-mode trx --short-message "test"  --sn 4
`

В **bind** всегда будет подставляться **0**. А не переданное в опции **--sn** значение **4+1**.

```
pdu: bind_transceiver
 .....
  sequence_number: 0
.....
```
В  **bind_transmitter_resp** вернет верное значение **--sn + 1  => 5**

```
 pdu:  bind_transmitter_resp
 .....
  sequence_number: 5
.....
```

**Comment by savonarola** [comment]
Пакеты выводятся до отправки в клиент, а sn проставляется клиентом.
